### ISSUE TITLE
CommentCount doesn't work if providing a new disqus_identifier

### ISSUE THREAD

**Issue by ZLevine** [tterb/gatsby-plugin-disqus#9] opened 2019-10-30 16:54 UTC
**Describe the bug**  
For sites that **do not** currently have a `disqus_identifier` set, setting one makes `<CommentCount />` not work (it always shows the placeholder textinstead). The `<Disqus />` comments component still works properly under these conditions.

Per the Disqus docs, `disqus_identifier` is optional but recommended; if you didn't have one set previously, you can start using one simply by adding it—your comments will continue to work properly.

The issue is we're migrating our site to Gatsby, and I want to start setting `disqus_identifier` now. I did so by passing `identifier` as such:

```
    // comments work properly
    const config = {
        url: url,
        title: title,
        identifier: guid,
    };

    <Disqus config={config} />
```

```
    // comments work, count does not
    const config = {
        url: url,
        title: title,
        identifier: guid,
    };
    const countConfig = {
        url: url,
        title: title,
        identifier: guid,
    };

    <Disqus config={config} />
    <CommentCount config={countConfig} />
```

```
    // both comments and counts work
    const config = {
        url: url,
        title: title,
        identifier: guid,
    };
    const countConfig = {
        url: url,
        title: title,
    };

<Disqus config={config} />
<CommentCount config={countConfig} />
```

I'm guessing the `CommentCount` lookup is done by identifier. I could omit identifier for that, but it would be nice to use the same config for both.

**To Reproduce**  
  1. Add both `CommentCount` and `Disqus` on a site that currently has no `disqus_identifier` set.
  2. Specify the `identifier` prop for both.
  3. Observe that the `Disqus` component works correctly but the `CommentCount` component always shows the placeholder string (`...`)
  4. Remove `identifier` from the `CommentCount` config
  5. Observe comment counts now work

**Expected behavior**  
I expect both the Disqus and CommentCount components to work correctly when specifying a new `disqus_identifier`

**Screenshots**  
![image](https://user-images.githubusercontent.com/4452484/67879851-07c85d00-fb14-11e9-9455-a11ba501cf5e.png)

![image](https://user-images.githubusercontent.com/4452484/67879888-14e54c00-fb14-11e9-9d99-3e8ccb50b9c8.png)

**Specifications:**
 - OS: macOS Catalina 10.15
 - Package version: 1.1.4
 - Gatsby version: 2.16.5

**Additional context**  
Please see my detailed description above. Thanks!

**Comment by ZLevine** [comment] 2019-10-30 17:10
Ah, it looks like the `<Disqus />` component _isn't_ rendering comments after all if I use `identifier`; this is super weird, it definitely seemed to work earlier. Must have been caching or something.

Closing this issue as it's a Disqus limitation despite their docs, not an issue with `gatsby-plugin-disqus`. Thanks for your great work!

**Comment by tterb** [comment] 2019-11-03 06:20
@ZLevine That sounds odd. I'm gonna open this up temporarily so I can remember to look into this in the next couple of days and make sure it's not an issue with the plugin. 

I would also recommend using the `identifier` to prevent lost threads when changing URLs.

**Comment by ZLevine** [comment] 2019-11-04 15:48
Sounds great, let me know if you need any help testing.

> I would also recommend using the `identifier` to prevent lost threads when changing URLs.

I agree—this is why I'd love to use `identifier` and should have from the beginning. You _can_ use their [Redirect Crawler](https://help.disqus.com/en/articles/1717126-redirect-crawler) when you change URLs, but this is a manual process so it's not ideal.

**Comment by tterb** [comment] 2019-11-29 09:28
@ZLevine I've tested this using the `identifier` parameter a few times and haven't been able to reproduce this issue. 
Do you have a repo that I could try to use to reproduce it?

**Comment by tterb** [comment] 2020-02-24 19:31
@ZLevine Were you able to resolve this issue?

**Comment by ZLevine** [comment] 2020-02-24 19:44
@tterb Sorry I missed your other comment! I’ll test it out tomorrow and post back here.

**Comment by arhoy** [comment] 2020-04-14 09:11
Has anyone resolved this? I am facing the same issue following the docs, the comment count is not working. Also is there current options on styling the disqus?

When I add a comment, the comment count  on the disqus component gets added but not on the CommentCount component. I am trying to create something similar like yahoo new with the Comment Count in the top of the article and the disqus below

Thank You

**Comment by tterb** [comment] 2020-04-14 20:09
@arhoy There weren't any changes made to resolve this, but these issues are usually due to a problem with an individual implementation rather than an issue in the component. Do you have a repo that could be used to reproduce your issue?

Additionally, I'm not sure I understand what you're trying to style but the Disqus component should automatically adapt to the style of your page.

**Comment by arhoy** [comment] 2020-04-14 20:24
I see thanks @tterb 
Here is repo I am currently trying to get this to work
https://github.com/arhoy/codepaper.dev

To clarify about the styles I meant change the background color of the disqus, the do not sell my data thing at the bottom, the font-styling of the comments etc.

I have tried now two different solutions online and when I add a comment it does not update the count.

**Comment by tterb** [comment] 2020-04-14 20:31
Thanks, I'll try to reproduce the issue with your repo tonight.

As far as styling, you can configure the typeface in the [Disqus settings](https://disqus.com/admin/settings/general/) but you can't modify/remove aspects of the comment section without being on a paid plan with Disqus.

**Comment by arhoy** [comment] 2020-04-14 20:50
I see ok thanks for looking into this, I am very curious to understand and know the issue!

**Comment by tterb** [comment] 2020-04-16 04:38
@arhoy Sorry I didn't have time to look at this yesterday. 
I tried to clone and run the repo you provided locally but was getting the following build error:  
```
Cannot query field "allButterPost" on type "Query"  graphql/template-strings
```
Regardless, I was able to take a look at the code and it looks like you have both [`disqus-react`](https://github.com/Disqus/disqus-react) and [`gatsby-plugin-disqus`](https://github.com/tterb/gatsby-plugin-disqus) in your dependencies, but you're actually only using `disqus-react`.
This package was originally created when `disqus-react` was unmaintained, though it has since been updated and now the two packages are very similar in their functionality, though this package provides some ease-of-use improvements for GatsbyJS.

As for potential solutions, I saw that locally you seem to be passing a `http://localhost:8000` URL to the `disqusConfig`, which can at times cause unexpected results because Disqus has a thread that correlating to the provided `shortname` and `identifier` but doesn't match the passed `url`.
Additionally, when I visited https://codepaper.dev/blog/sql-excel-automation-every-analyst-should-know it appears that the comment count is appearing in production.

<img width="640" alt="screenshot" src="https://user-images.githubusercontent.com/16360374/79414851-9c0e6b00-7f60-11ea-89ad-bfc3dc6e14cc.png">

So I believe that your issue should be resolved if you try to passing the production URL to the `disqusConfig`.

Let me know if this resolves your issue.

**Comment by arhoy** [comment] 2020-04-16 04:46
@tterb no problem! 
I tried testing it it seems the comment count is not updating in real time but it does eventually show which really is strange
Here is the prod version
https://codepaper.dev/blog/sql-excel-automation-every-analyst-should-know

As for the buttercms issue, that is because there is no local verison of butter in your .env.development file.

Not sure how I can duplicate without not as each post comes from butter and that is where I have the disqus comments.
If you add a comment, you might see that as well I believe

**Comment by tterb** [comment] 2020-04-16 04:53
@arhoy The comment count does not update in realtime because it relies on a Disqus script that is currently being very heavily cached. Though this is will hopefully be adjusted in the future.

Are you able to confirm that passing the production url to the `disqusConfig` fixes your problem with the comment count not being displayed locally?

**Comment by arhoy** [comment] 2020-04-16 05:35
I believe it is the same issue in both cases.  Comment count being delayed in prod and in dev.

Thanks for locating the issue. Guess there is not much I can do then

**Comment by tterb** [comment] 2020-04-17 05:23
Okay, then I'm going to close this issue for now.

**Closed as completed by tterb** 2020-04-17 05:23 UTC
